apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-management-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: user-management-service
        image: brandontqnguyen/project-tracker_user-management-service
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: ClusterIP
  ports:
  # - name: http
  #   protocol: TCP
    - port: 80
    # targetPort: 80
  # - name: https
  #   protocol: TCP
  #   port: 443
  #   targetPort: 443
  selector:
    app: user-management-service