apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: project-management-frontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: project-management-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: project-management-frontend
        image: brandontqnguyen/project-tracker_project-management-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-resource-group: brandon-poc-rg
  name: project-management-frontend
spec:
  # loadBalancerIP: 52.188.220.64
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: project-management-frontend
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: pm-ui
spec:
  prefix: /
  service: project-management-frontend:80
---
apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: tls
spec:
  hosts: ["*"]
  secret: tls-cert