---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  loadBalancerIP: 40.121.209.53
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    service: ambassador
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: pm-ui
spec:
  cors:
    origins: "*"
  prefix: /
  service: project-management-frontend:80
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: pm-ums
spec:
  cors:
    origins: "*"
  prefix: /ums/
  service: user-management-service:80
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: pm-pms
spec:
  cors:
    origins: "*"
  prefix: /pms/
  service: project-management-service:80
---
# apiVersion: getambassador.io/v1
# kind: TLSContext
# metadata:
  # name: tls
# spec:
  # hosts: ["*"]
  # secret: tls-cert
# ---