---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  loadBalancerIP: 52.224.139.134
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - name: https
     port: 443
     protocol: TCP
     targetPort: 8443
  selector:
    service: ambassador
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: pm-ui
spec:
  prefix: /
  service: project-management-frontend:80
---
apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: tls
spec:
  hosts: ["*"]
  secret: tls-cert