---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  loadBalancerIP: 52.224.139.134
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - name: https
     port: 443
     protocol: TCP
     targetPort: 8443
  selector:
    service: ambassador