apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: project-management-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: project-management-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: project-management-frontend
        image: brandontqnguyen/project-management-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: project-management-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: project-management-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: project-management-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: project-management-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: project-management-s
        image: brandontqnguyen/project-management-service
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: project-management-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: project-management-service