apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: token-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: token-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: token-service
        image: brandontqnguyen/token-service:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        livenessProbe:
          httpGet:
              path: /health
              port: 80
              httpHeaders:
              - name: Custom-Header
                value: Awesome
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
              path: /health
              port: 80
              httpHeaders:
              - name: Custom-Header
                value: Awesome
          initialDelaySeconds: 60
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: token-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: token-service